name: Update Dashboard Stats

on:
  schedule:
    - cron: "0 */6 * * *" # Every 6 hours
  workflow_dispatch: # Manual trigger

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.THE_CORE_DUMP }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Fetch Stats
        env:
          CHESSMAN_TOKEN: ${{ secrets.GOATCOUNTER_SECRET }}
          EXECUTABLES_TOKEN: ${{ secrets.GOATCOUNTER_SECRET }}
          EXPLORINGOS_TOKEN: ${{ secrets.GOATCOUNTER_SECRET }}
          LEARNINGRESOURCE_TOKEN: ${{ secrets.GOATCOUNTER_SECRET }}
          LEGACY_TOKEN: ${{ secrets.GOATCOUNTER_SECRET }}
          OSJOURNEY_TOKEN: ${{ secrets.GOATCOUNTER_SECRET }}
          REVERSINGBITS_TOKEN: ${{ secrets.GOATCOUNTER_SECRET }}
        run: |
          node .github/scripts/fetch-stats.js

      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.THE_CORE_DUMP }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add _data/dashboard.json
          git diff --staged --quiet || git commit -m "Update dashboard stats [skip ci]"
          git push https://$GITHUB_TOKEN@github.com/mohitmishra786/TheCoreDump.git
